name = "ive"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "ReversiDO"
class_name = "ReversiDO"

# --- Durable Object migrations ---

[[migrations]]
tag = "vxx"
//delete_classes = ["CounterDO"]
//new_classes = ["ReversiDO"]


# 初回作成時はこちらを有効にする
new_sqlite_classes = ["ReversiDO"]

# 既に作成済みの DO を再利用するときはこちらを使う
#new_classes = ["ReversiDO"]